blueprint:
  name: Thermostat ON/OFF météo + auto-absence + logs
  description: >
    Thermostat simple ON/OFF avec :
    - compensation climatique via météo
    - détecteur automatique d'absence
    - déclenchement toutes les minutes
    - logs détaillés
    - notification en cas d'erreur
  domain: automation

  input:
    temp_sensor:
      name: Capteur de température intérieure
      selector:
        entity:
          domain: sensor

    heater_switch:
      name: Switch du radiateur
      selector:
        entity:
          domain: switch

    weather_entity:
      name: Source météo Home Assistant
      selector:
        entity:
          domain: weather

    mode_select:
      name: Sélecteur de mode chauffage
      selector:
        entity:
          domain: input_select

    presence_tracker:
      name: Tracker de présence
      selector:
        entity:
          domain: device_tracker

    home_zone:
      name: Zone Maison
      selector:
        entity:
          domain: zone

    notify_service:
      name: Service de notification
      description: "Exemple : notify.mobile_app_iphone"
      selector:
        action: {}

    comfort_temp:
      name: Température Confort
      default: 21
      selector:
        number:
          min: 5
          max: 30
          step: 0.5

    eco_temp:
      name: Température Eco
      default: 19
      selector:
        number:
          min: 5
          max: 30
          step: 0.5

    away_temp:
      name: Température Absent
      default: 17
      selector:
        number:
          min: 5
          max: 30
          step: 0.5

    outdoor_reference:
      name: Température extérieure de référence
      default: 15
      selector:
        number:
          min: -10
          max: 30
          step: 1

    climate_factor:
      name: Facteur de compensation climatique
      default: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.01

mode: single

trigger:
  - platform: state
    entity_id: !input temp_sensor

  - platform: state
    entity_id: !input weather_entity

  - platform: state
    entity_id: !input mode_select

  - platform: state
    entity_id: !input presence_tracker

  # Déclenchement toutes les minutes
  - platform: time_pattern
    minutes: "*"

action:

  ####################################################
  # VALIDATION DES CAPTEURS + NOTIFICATIONS ERREURS
  ####################################################
  - variables:
      inside_raw: "{{ states[inputs.temp_sensor].state }}"
      outside_raw: "{{ state_attr(inputs.weather_entity, 'temperature') }}"

  - choose:
      - conditions: "{{ inside_raw in ['unknown','unavailable','none','None'] }}"
        sequence:
          - service: !input notify_service
            data:
              message: "ERREUR : Le capteur de température intérieure est indisponible."
          - service: system_log.write
            data:
              level: error
              message: "Thermostat ERROR: inside temperature sensor unavailable."
          - stop: "Température intérieure invalide"

      - conditions: "{{ outside_raw in ['unknown','unavailable', None] }}"
        sequence:
          - service: !input notify_service
            data:
              message: "ERREUR : La météo ne retourne pas la température extérieure."
          - service: system_log.write
            data:
              level: error
              message: "Thermostat ERROR: external temperature unavailable."
          - stop: "Température extérieure invalide"

  ####################################################
  # AUTO-MODE ABSENT BASÉ SUR LA PRÉSENCE
  ####################################################
  - choose:
      - conditions: "{{ not is_state(inputs.presence_tracker, 'home') }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_select
            data:
              option: 'absent'
          - service: system_log.write
            data:
              level: info
              message: "Thermostat: Mode absent activé (départ de la zone)."

      - conditions: >
          {{ is_state(inputs.presence_tracker, 'home') 
             and states[inputs.mode_select].state == 'absent' }}
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_select
            data:
              option: 'eco'
          - service: system_log.write
            data:
              level: info
              message: "Thermostat: Retour à la maison → mode eco."

  ####################################################
  # RÉGULATION + COMPENSATION CLIMATIQUE
  ####################################################
  - variables:
      mode: "{{ states[inputs.mode_select].state }}"
      inside_temp: "{{ inside_raw | float }}"
      outside_temp: "{{ outside_raw | float }}"
      base_target_temp: >-
        {% if mode == 'confort' %}
          {{ inputs.comfort_temp }}
        {% elif mode == 'eco' %}
          {{ inputs.eco_temp }}
        {% else %}
          {{ inputs.away_temp }}
        {% endif %}
      diff: "{{ (inputs.outdoor_reference | float) - outside_temp }}"
      climate_correction: >-
        {% if diff > 0 %}
          {{ diff * (inputs.climate_factor | float) }}
        {% else %}
          0
        {% endif %}
      target_temp: "{{ base_target_temp + climate_correction }}"

  - service: system_log.write
    data:
      level: info
      message: >
        Thermostat: Mode={{ mode }},
        Inside={{ inside_temp }}°C,
        Outside={{ outside_temp }}°C,
        Target={{ target_temp }}°C
        (base={{ base_target_temp }} + corr={{ climate_correction }})

  ####################################################
  # COMMANDE DU RADIATEUR
  ####################################################
  - choose:
      - conditions: "{{ inside_temp < target_temp }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input heater_switch
          - service: system_log.write
            data:
              level: info
              message: "Thermostat: Chauffage → ON"

      - conditions: "{{ inside_temp > target_temp }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - service: system_log.write
            data:
              level: info
              message: "Thermostat: Chauffage → OFF"
