blueprint:
  name: Thermostat Complet (Final Fix)
  description: >
    Thermostat avec correction syntaxique stricte.
    Gère: Boost, Absence, Nuit (passage minuit inclus), Météo.
  domain: automation

  input:
    temp_sensor:
      name: Capteur température intérieure
      selector:
        entity:
          domain: sensor
    heater_switch:
      name: Switch radiateur
      selector:
        entity:
          domain: switch
    weather_entity:
      name: Entité météo
      selector:
        entity:
          domain: weather
    presence_tracker:
      name: Tracker téléphone
      selector:
        entity:
          domain: device_tracker
    mode_select:
      name: Mode chauffage (input_select)
      description: "Options requises : confort, eco, nuit, absent"
      selector:
        entity:
          domain: input_select
    boost_button:
      name: Bouton Boost (input_boolean)
      selector:
        entity:
          domain: input_boolean
    
    # Helpers obligatoires
    target_temp_helper:
      name: Helper stockage Consigne (input_number)
      description: "Créez un input_number pour voir la consigne calculée."
      selector:
        entity:
          domain: input_number
    mode_display_helper:
      name: Helper affichage Mode Réel (input_text)
      description: "Créez un input_text pour voir le mode actif (ex: Boost)."
      selector:
        entity:
          domain: input_text

    # Paramètres
    comfort_temp:
      name: Température confort
      default: 21
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
    eco_temp:
      name: Température éco
      default: 19
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
    night_temp:
      name: Température nuit
      default: 18
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
    away_temp:
      name: Température absent
      default: 17
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
    boost_temp:
      name: Température boost
      default: 23
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
    outdoor_reference:
      name: "Température ext. référence (15°C par défaut)"
      default: 15
      selector:
        number:
          min: -10
          max: 30
          step: 1
    climate_factor:
      name: "Facteur climatique (0.1 = fort, 0 = désactivé)"
      default: 0.1
      selector:
        number:
          min: 0
          max: 2
          step: 0.01
    hysteresis:
      name: Hystérésis
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 2.0
          step: 0.1
    night_start:
      name: Heure début nuit
      default: "23:00:00"
      selector:
        time:
    night_end:
      name: Heure fin nuit
      default: "07:00:00"
      selector:
        time:

mode: single

trigger:
  - platform: time_pattern
    seconds: "/30"
  - platform: state
    entity_id: !input temp_sensor
  - platform: state
    entity_id: !input mode_select
  - platform: state
    entity_id: !input boost_button

action:
  ##########################################################
  # ÉTAPE 1 : MAPPER LES INPUTS DANS DES VARIABLES
  ##########################################################
  - variables:
      # Entités
      entity_temp: !input temp_sensor
      entity_weather: !input weather_entity
      entity_heater: !input heater_switch
      entity_tracker: !input presence_tracker
      entity_mode: !input mode_select
      entity_boost: !input boost_button
      entity_target_helper: !input target_temp_helper
      entity_mode_helper: !input mode_display_helper
      
      # Valeurs Numériques
      conf_boost: !input boost_temp
      conf_comfort: !input comfort_temp
      conf_eco: !input eco_temp
      conf_night: !input night_temp
      conf_away: !input away_temp
      conf_outdoor_ref: !input outdoor_reference
      conf_climate_factor: !input climate_factor
      conf_hysteresis: !input hysteresis
      
      # Horaires
      time_start: !input night_start
      time_end: !input night_end

  ##########################################################
  # ÉTAPE 2 : CALCULS JINJA
  ##########################################################
  - variables:
      inside_temp: "{{ states(entity_temp) | float(0) }}"
      outside_temp: "{{ state_attr(entity_weather, 'temperature') | float(0) }}"
      is_boost: "{{ is_state(entity_boost, 'on') }}"
      current_mode: "{{ states(entity_mode) }}"
      is_home: "{{ is_state(entity_tracker, 'home') }}"
      now_str: "{{ now().strftime('%H:%M:%S') }}"

  ##########################################################
  # LOGIQUE : BOOST PRIORITAIRE
  ##########################################################
  - choose:
      - conditions: "{{ is_boost }}"
        sequence:
          - variables:
              target: "{{ conf_boost | float }}"
          
          # Action Switch
          - choose:
              - conditions: "{{ inside_temp < (target - conf_hysteresis) }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input heater_switch
              - conditions: "{{ inside_temp > (target + conf_hysteresis) }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input heater_switch
          
          # Mise à jour Helpers
          - service: input_number.set_value
            target:
              entity_id: !input target_temp_helper
            data:
              value: "{{ target }}"
          - service: input_text.set_value
            target:
              entity_id: !input mode_display_helper
            data:
              value: "BOOST"
              
          - stop: "Mode Boost actif"

  ##########################################################
  # LOGIQUE : AUTO-ABSENCE
  ##########################################################
  - choose:
      - conditions: "{{ not is_home }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_select
            data:
              option: "absent"
      - conditions: "{{ is_home and current_mode == 'absent' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_select
            data:
              option: "eco"

  ##########################################################
  # LOGIQUE : MODE NUIT (Gestion minuit incluse)
  ##########################################################
  - variables:
      is_night: >-
        {% if time_start > time_end %}
          {{ now_str >= time_start or now_str <= time_end }}
        {% else %}
          {{ time_start <= now_str <= time_end }}
        {% endif %}
  
  - choose:
      - conditions: "{{ is_night }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_select
            data:
              option: "nuit"
      - conditions: "{{ not is_night and current_mode == 'nuit' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_select
            data:
              option: "eco"

  ##########################################################
  # LOGIQUE : CALCUL CONSIGNE FINALE
  ##########################################################
  - variables:
      # On relit le mode car il a pu changer (nuit/absent)
      final_mode: "{{ states(entity_mode) }}"
      
      base_target: >-
        {% if final_mode == 'confort' %} {{ conf_comfort }}
        {% elif final_mode == 'eco' %} {{ conf_eco }}
        {% elif final_mode == 'nuit' %} {{ conf_night }}
        {% elif final_mode == 'absent' %} {{ conf_away }}
        {% else %} {{ conf_comfort }} {% endif %}
      
      diff: "{{ (conf_outdoor_ref | float) - outside_temp }}"
      # Si diff > 0 (il fait plus froid que la ref), on chauffe plus
      climate_corr: >-
        {% if diff > 0 %}
          {{ diff * (conf_climate_factor | float) }}
        {% else %} 0 {% endif %}
      
      final_target: "{{ (base_target | float) + (climate_corr | float) }}"

  ##########################################################
  # ACTIONS FINALES
  ##########################################################
  
  # 1. Mise à jour des helpers pour affichage
  - service: input_number.set_value
    target:
      entity_id: !input target_temp_helper
    data:
      value: "{{ final_target | round(1) }}"
      
  - service: input_text.set_value
    target:
      entity_id: !input mode_display_helper
    data:
      value: "{{ final_mode }}"

  # 2. Pilotage du radiateur
  - choose:
      - conditions: "{{ inside_temp < (final_target - conf_hysteresis) }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input heater_switch
      - conditions: "{{ inside_temp > (final_target + conf_hysteresis) }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
