blueprint:
  name: Thermostat Complet (Fix & Helpers)
  description: >
    Thermostat ON/OFF avec compensation météo, gestion Nuit/Absence/Boost
    et mise à jour d'entités Helpers pour l'affichage (input_number/input_text).
  domain: automation

  input:
    temp_sensor:
      name: Capteur température intérieure
      selector:
        entity:
          domain: sensor

    heater_switch:
      name: Switch radiateur
      selector:
        entity:
          domain: switch

    weather_entity:
      name: Entité météo
      selector:
        entity:
          domain: weather

    presence_tracker:
      name: Tracker téléphone
      selector:
        entity:
          domain: device_tracker

    mode_select:
      name: Mode chauffage (input_select)
      description: "Options requises : confort, eco, nuit, absent"
      selector:
        entity:
          domain: input_select

    boost_button:
      name: Bouton Boost (input_boolean)
      selector:
        entity:
          domain: input_boolean

    # --- Helpers pour l'affichage (Optionnels mais recommandés) ---
    target_temp_helper:
      name: Helper Affichage Consigne (input_number)
      description: "Entité pour stocker la température cible calculée."
      default: ""
      selector:
        entity:
          domain: input_number
    
    mode_display_helper:
      name: Helper Affichage Mode (input_text)
      description: "Entité pour afficher le mode actif (ex: 'BOOST' ou 'ECO')."
      default: ""
      selector:
        entity:
          domain: input_text

    # --- Températures ---
    comfort_temp:
      name: Température Confort
      default: 21
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
    
    eco_temp:
      name: Température Eco
      default: 19
      selector:
        number:
          min: 10
          max: 30
          step: 0.5

    night_temp:
      name: Température Nuit
      default: 18
      selector:
        number:
          min: 10
          max: 30
          step: 0.5

    away_temp:
      name: Température Absent
      default: 16
      selector:
        number:
          min: 5
          max: 30
          step: 0.5

    boost_temp:
      name: Température Boost
      default: 23
      selector:
        number:
          min: 10
          max: 30
          step: 0.5

    # --- Paramètres avancés ---
    outdoor_reference:
      name: Température ext. de référence
      description: "Température extérieure où la compensation commence (défaut 15°C)."
      default: 15
      selector:
        number:
          min: -10
          max: 30
          step: 1

    climate_factor:
      name: Facteur climatique
      description: "Correction ajoutée par degré de différence ext (0 = désactivé)."
      default: 0.1
      selector:
        number:
          min: 0
          max: 2
          step: 0.05

    hysteresis:
      name: Hystérésis
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 3
          step: 0.1

    night_start:
      name: Heure début nuit
      default: "23:00:00"
      selector:
        time:

    night_end:
      name: Heure fin nuit
      default: "07:00:00"
      selector:
        time:

mode: single

trigger:
  - platform: time_pattern
    seconds: "/30"
  - platform: state
    entity_id: !input temp_sensor
  - platform: state
    entity_id: !input mode_select
  - platform: state
    entity_id: !input boost_button

action:
  # ------------------------------------------------------
  # 1. DEFINITION DES VARIABLES (Mapping propre des inputs)
  # ------------------------------------------------------
  - variables:
      # Entités
      e_temp: !input temp_sensor
      e_weather: !input weather_entity
      e_mode: !input mode_select
      e_boost: !input boost_button
      e_tracker: !input presence_tracker
      e_switch: !input heater_switch
      e_target_help: !input target_temp_helper
      e_mode_help: !input mode_display_helper

      # Valeurs
      t_conf: !input comfort_temp
      t_eco: !input eco_temp
      t_night: !input night_temp
      t_away: !input away_temp
      t_boost: !input boost_temp
      
      # Params
      v_out_ref: !input outdoor_reference
      v_clim_factor: !input climate_factor
      v_hys: !input hysteresis
      v_night_start: !input night_start
      v_night_end: !input night_end

  # ------------------------------------------------------
  # 2. LOGIQUE ET CALCULS
  # ------------------------------------------------------
  - variables:
      current_temp: "{{ states(e_temp) | float(0) }}"
      outside_temp: "{{ state_attr(e_weather, 'temperature') | float(0) }}"
      is_boost: "{{ is_state(e_boost, 'on') }}"
      is_home: "{{ is_state(e_tracker, 'home') }}"
      manual_mode: "{{ states(e_mode) }}"
      now_str: "{{ now().strftime('%H:%M:%S') }}"

      # Détection Auto Nuit (Gère minuit)
      is_night_time: >-
        {% if v_night_start > v_night_end %}
          {{ now_str >= v_night_start or now_str <= v_night_end }}
        {% else %}
          {{ v_night_start <= now_str <= v_night_end }}
        {% endif %}

      # Détermination du mode réel (Priorité: Boost > Absent > Nuit > Manuel)
      real_mode: >-
        {% if is_boost %}
          boost
        {% elif not is_home %}
          absent
        {% elif is_night_time and manual_mode != 'confort' %}
          nuit
        {% else %}
          {{ manual_mode }}
        {% endif %}

      # Sélection température de base
      base_target: >-
        {% if real_mode == 'boost' %} {{ t_boost }}
        {% elif real_mode == 'absent' %} {{ t_away }}
        {% elif real_mode == 'nuit' %} {{ t_night }}
        {% elif real_mode == 'eco' %} {{ t_eco }}
        {% else %} {{ t_conf }} {% endif %}

      # Calcul compensation climatique (Plus il fait froid dehors par rapport à la ref, plus on chauffe)
      clim_correction: >-
        {% set diff = (v_out_ref | float) - outside_temp %}
        {% if diff > 0 %}
          {{ diff * (v_clim_factor | float) }}
        {% else %}
          0
        {% endif %}

      # Consigne finale
      final_target: "{{ (base_target | float) + (clim_correction | float) }}"

  # ------------------------------------------------------
  # 3. ACTIONS
  # ------------------------------------------------------
  
  # A. Synchroniser le selecteur de mode si nécessaire (visuel)
  - choose:
      - conditions: "{{ real_mode in ['confort', 'eco', 'nuit', 'absent'] and manual_mode != real_mode }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_select
            data:
              option: "{{ real_mode }}"

  # B. Mettre à jour les helpers d'affichage (si définis)
  - choose:
      - conditions: "{{ e_target_help != none }}"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input target_temp_helper
            data:
              value: "{{ final_target | round(1) }}"
  
  - choose:
      - conditions: "{{ e_mode_help != none }}"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: !input mode_display_helper
            data:
              value: "{{ real_mode | upper }}"

  # C. Pilotage du Radiateur (Log ON/OFF avec Hystérésis)
  - choose:
      # Allumage
      - conditions: "{{ current_temp < (final_target - v_hys) }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input heater_switch
          - service: system_log.write
            data:
              level: info
              message: "Thermostat ON: Temp {{ current_temp }} < Cible {{ final_target }}"

      # Extinction
      - conditions: "{{ current_temp > (final_target + v_hys) }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - service: system_log.write
            data:
              level: info
              message: "Thermostat OFF: Temp {{ current_temp }} > Cible {{ final_target }}"
